"""hook auth

Revision ID: 29fb7a700944
Revises: e4aaee4e1fd8
Create Date: 2022-12-31 22:30:04.918642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '29fb7a700944'
down_revision = 'e4aaee4e1fd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('webhook_key', sa.Column('hook_auth', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###
    op.drop_column('schema_version', 'hook_auth')
    op.add_column('schema_version', sa.Column('hook_auth', postgresql.JSONB(astext_type=sa.Text()), nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('webhook_key', 'hook_auth')
    # ### end Alembic commands ###
    op.drop_column('schema_version', 'hook_auth')
    op.add_column('schema_version', sa.Column('hook_auth', sa.String(), nullable=True))
