"""fkey cascades

Revision ID: 3aeb46b2a185
Revises: 84367b3f1261
Create Date: 2022-12-29 19:43:07.810137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3aeb46b2a185'
down_revision = '84367b3f1261'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('schema_version_tschema_id_fkey', 'schema_version', type_='foreignkey')
    op.create_foreign_key(None, 'schema_version', 'task_schema', ['tschema_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_user_id_fkey', 'task', type_='foreignkey')
    op.drop_constraint('task_ttype_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'ab_user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task', 'task_type', ['ttype_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('task_history_editor_id_fkey', 'task_history', type_='foreignkey')
    op.drop_constraint('task_history_assigned_id_fkey', 'task_history', type_='foreignkey')
    op.drop_constraint('task_history_task_id_fkey', 'task_history', type_='foreignkey')
    op.create_foreign_key(None, 'task_history', 'ab_user', ['editor_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task_history', 'task', ['task_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'task_history', 'ab_user', ['assigned_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('task_type_version_id_fkey', 'task_type', type_='foreignkey')
    op.create_foreign_key(None, 'task_type', 'schema_version', ['version_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('webhook_key_tschema_id_fkey', 'webhook_key', type_='foreignkey')
    op.create_foreign_key(None, 'webhook_key', 'task_schema', ['tschema_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'webhook_key', type_='foreignkey')
    op.create_foreign_key('webhook_key_tschema_id_fkey', 'webhook_key', 'task_schema', ['tschema_id'], ['id'])
    op.drop_constraint(None, 'task_type', type_='foreignkey')
    op.create_foreign_key('task_type_version_id_fkey', 'task_type', 'schema_version', ['version_id'], ['id'])
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.drop_constraint(None, 'task_history', type_='foreignkey')
    op.create_foreign_key('task_history_task_id_fkey', 'task_history', 'task', ['task_id'], ['id'])
    op.create_foreign_key('task_history_assigned_id_fkey', 'task_history', 'ab_user', ['assigned_id'], ['id'])
    op.create_foreign_key('task_history_editor_id_fkey', 'task_history', 'ab_user', ['editor_id'], ['id'])
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_ttype_id_fkey', 'task', 'task_type', ['ttype_id'], ['id'])
    op.create_foreign_key('task_user_id_fkey', 'task', 'ab_user', ['user_id'], ['id'])
    op.drop_constraint(None, 'schema_version', type_='foreignkey')
    op.create_foreign_key('schema_version_tschema_id_fkey', 'schema_version', 'task_schema', ['tschema_id'], ['id'])
    # ### end Alembic commands ###
