"""json -> jsonb

Revision ID: 7bc7c406e433
Revises: 5be5733253a9
Create Date: 2022-12-24 11:52:58.155684

"""
from alembic import op
import sqlalchemy as sa, sqlmodel
from sqlalchemy.dialects.postgresql import JSONB


# revision identifiers, used by Alembic.
revision = '7bc7c406e433'
down_revision = '5be5733253a9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column('taskhistory', 'update_meta', nullable=True, type_=JSONB())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.alter_column('taskhistory', 'update_meta', nullable=True, type_=sa.JSON())
