"""remove id from apikey

Revision ID: c316ae20eae5
Revises: d24615e15f70
Create Date: 2022-12-30 12:55:49.075949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c316ae20eae5'
down_revision = 'd24615e15f70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_key', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_key', sa.Column('id', postgresql.UUID(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
