"""preserve tasks when deleting user

Revision ID: d24615e15f70
Revises: 3aeb46b2a185
Create Date: 2022-12-30 10:21:24.660303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd24615e15f70'
down_revision = '3aeb46b2a185'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_user_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'ab_user', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_user_id_fkey', 'task', 'ab_user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
